<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Teacher Schedule Management</title>
    <link rel="stylesheet" href="schedule.css">
</head>
<body>

    <!-- Sidebar -->
    <div class="sidebar">
        <h2>Teacher Panel</h2>
        <ul>
            <li><a href="/teacher/dashboard">Dashboard</a></li>
            <li><a href="/teacher/attendance">Attendance</a></li>
            <li><a href="/teacher/grades" >Grade Management</a></li>
            <li><a href="/teacher/studentReports">Student Reports</a></li>
            <li><a href="/teacher/messages">Messages</a></li>
            <li><a href="/teacher/schedule" class="active">Schedule</a></li>
            <li><a href="/teacher/settings">Settings</a></li>
        </ul>
    </div>

    <!-- Main Content -->
    <div class="main-content">
        <header class="header">
            <h1>📅 Teacher Schedule Management</h1>
            <button class="add-schedule-btn">+ Add Schedule</button>
        </header>

        <!-- Schedule Calendar -->
        <div class="schedule-container">
            <div class="calendar">
                <div class="calendar-header">
                    <button class="prev-month">&lt;</button>
                    <h2 id="monthYear">March 2025</h2>
                    <button class="next-month">&gt;</button>
                </div>
                <div class="calendar-grid">
                    <!-- Days of the week -->
                    <div class="day-label">Sun</div>
                    <div class="day-label">Mon</div>
                    <div class="day-label">Tue</div>
                    <div class="day-label">Wed</div>
                    <div class="day-label">Thu</div>
                    <div class="day-label">Fri</div>
                    <div class="day-label">Sat</div>
                    
                    <!-- Calendar Days (Generated by JS) -->
                </div>
            </div>

            <!-- Schedule List -->
            <div class="schedule-list">
                <h3>📌 Scheduled Classes</h3>
                <ul id="scheduleItems">
                    <li>
                        <strong>March 5, 2025</strong> - Mathematics (Grade 10) at 10:00 AM
                        <button class="edit-btn">Edit</button>
                        <button class="delete-btn">Delete</button>
                    </li>
                    <li>
                        <strong>March 8, 2025</strong> - Science (Grade 9) at 2:00 PM
                        <button class="edit-btn">Edit</button>
                        <button class="delete-btn">Delete</button>
                    </li>
                </ul>
            </div>
        </div>

        <!-- Add Schedule Form -->
        <div class="add-schedule-popup">
            <div class="popup-content">
                <h2>Add New Schedule</h2>
                <label>Date:</label>
                <input type="date" id="scheduleDate">
                <label>Subject:</label>
                <input type="text" id="scheduleSubject" placeholder="Enter Subject">
                <label>Time:</label>
                <input type="time" id="scheduleTime">
                <label>Class:</label>
                <input type="text" id="scheduleClass" placeholder="Grade Level / Section">
                <button class="save-schedule">Save</button>
                <button class="close-popup">Cancel</button>
            </div>
        </div>
    </div>

    <script src="schedule.js"></script>
</body>
</html>
<style>
/* General Styles */
* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
    font-family: 'Poppins', sans-serif;
}

body {
    display: flex;
    background-color: #f4f7fc;
    min-height: 100vh;
}

.sidebar {
    position: fixed;
    width: 250px;
    background-color: #2c3e50;
    color: white;
    padding: 20px;
    min-height: 100vh;
}

.sidebar h2 {
    text-align: center;
    margin-bottom: 20px;
}

.sidebar ul {
    list-style: none;
    padding: 0;
}

.sidebar ul li {
    margin: 15px 0;
}

.sidebar ul li a {
    color: white;
    text-decoration: none;
    display: block;
    padding: 10px;
    border-radius: 5px;
    transition: background 0.3s;
}

.sidebar ul li a.active, .sidebar ul li a:hover {
    background-color: #34495e;
}


/* Main Content */
.main-content {
    margin-left: 260px;
    padding: 20px;
    flex-grow: 1;
}

/* Header */
.header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    background: white;
    padding: 15px 20px;
    border-radius: 8px;
    box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1);
}

.header h1 {
    font-size: 22px;
    color: #333;
}

.add-schedule-btn {
    background: #27ae60;
    color: white;
    padding: 10px 15px;
    border: none;
    border-radius: 5px;
    cursor: pointer;
    transition: 0.3s;
}

.add-schedule-btn:hover {
    background: #219150;
}

/* Schedule Container */
.schedule-container {
    display: flex;
    gap: 20px;
    margin-top: 20px;
}

/* Calendar */
.calendar {
    background: white;
    padding: 20px;
    border-radius: 10px;
    box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);
    width: 60%;
}

.calendar-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 15px;
}

.calendar-header h2 {
    font-size: 18px;
    color: #333;
}

.calendar-header button {
    background: #2980b9;
    color: white;
    border: none;
    padding: 5px 10px;
    border-radius: 5px;
    cursor: pointer;
    transition: 0.3s;
}

.calendar-header button:hover {
    background: #1f6692;
}

.calendar-grid {
    display: grid;
    grid-template-columns: repeat(7, 1fr);
    gap: 10px;
}

.day-label {
    font-weight: bold;
    text-align: center;
    padding: 8px;
    background: #ecf0f1;
    border-radius: 5px;
}

.calendar-day {
    text-align: center;
    padding: 15px;
    background: #fff;
    border-radius: 5px;
    cursor: pointer;
    transition: 0.3s;
    border: 1px solid #ddd;
}

.calendar-day:hover {
    background: #3498db;
    color: white;
}

/* Schedule List */
.schedule-list {
    background: white;
    padding: 20px;
    border-radius: 10px;
    box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);
    width: 40%;
}

.schedule-list h3 {
    font-size: 18px;
    margin-bottom: 15px;
    color: #333;
}

.schedule-list ul {
    list-style: none;
}

.schedule-list li {
    padding: 12px;
    background: #f9f9f9;
    margin-bottom: 10px;
    border-radius: 5px;
    display: flex;
    justify-content: space-between;
    align-items: center;
}

.schedule-list .edit-btn,
.schedule-list .delete-btn {
    padding: 6px 10px;
    border: none;
    border-radius: 5px;
    cursor: pointer;
    transition: 0.3s;
}

.schedule-list .edit-btn {
    background: #f1c40f;
    color: white;
}

.schedule-list .edit-btn:hover {
    background: #d4ac0d;
}

.schedule-list .delete-btn {
    background: #e74c3c;
    color: white;
}

.schedule-list .delete-btn:hover {
    background: #c0392b;
}

/* Add Schedule Popup */
.add-schedule-popup {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: rgba(0, 0, 0, 0.5);
    display: none;
    justify-content: center;
    align-items: center;
}

.popup-content {
    background: white;
    padding: 20px;
    width: 400px;
    border-radius: 8px;
    box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.2);
    text-align: center;
}

.popup-content h2 {
    font-size: 20px;
    margin-bottom: 15px;
}

.popup-content label {
    display: block;
    margin-top: 10px;
    font-weight: bold;
}

.popup-content input {
    width: 100%;
    padding: 8px;
    margin-top: 5px;
    border: 1px solid #ccc;
    border-radius: 5px;
}

.popup-content .save-schedule,
.popup-content .close-popup {
    margin-top: 15px;
    padding: 10px;
    border: none;
    border-radius: 5px;
    cursor: pointer;
}

.popup-content .save-schedule {
    background: #2ecc71;
    color: white;
}

.popup-content .close-popup {
    background: #e74c3c;
    color: white;
}

</style>